apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - prometheus-service.yaml
  - prometheus-statefulset.yaml