apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: logging
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  selector:
    app: prometheus