apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: logging
  labels:
    app: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-serviceaccount
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0
          args:
            - '--storage.tsdb.retention=6h'
            - '--storage.tsdb.path=/prometheus/'
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'
          ports:
            - name: web
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: prometheus-volume
              mountPath: /prometheus
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
        fsGroup: 65534
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: prometheus-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"