version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "22:00"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 5
    assignees:
      - "SelahattinSert"
    labels:
      - "dependencies"
      - "maven"
    groups:
      spring-dependencies:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot*"
          - "io.micrometer*"
      azure-dependencies:
        patterns:
          - "com.azure.spring*"
          - "com.azure*"
