apiVersion: v1
kind: Service
metadata:
  name: camera-onboarding-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
      name: api
  type: NodePort