apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-onboarding
  template:
    metadata:
      labels:
        app: camera-onboarding
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: camera-onboarding
          image: mrsert/camera-onboarding:metrics-v2
          resources:
            requests:
              cpu: "275m"
              memory: "550Mi"
            limits:
              cpu: "275m"
              memory: "550Mi"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: camera-onboarding-secrets
          
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      imagePullSecrets:
        - name: acr-secret
