apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: logging
data:
  grafana.ini: |
    [server]
    http_port = 3000

    [auth.anonymous]
    enabled = true

    [security]
    admin_user = admin
    admin_password = admin
